// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frunner.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	frunner.proto

It has these top-level messages:
	Data
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "grpc.Data")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for FunctionRunner service

type FunctionRunnerClient interface {
	Run(ctx context.Context, opts ...grpc1.CallOption) (FunctionRunner_RunClient, error)
}

type functionRunnerClient struct {
	cc *grpc1.ClientConn
}

func NewFunctionRunnerClient(cc *grpc1.ClientConn) FunctionRunnerClient {
	return &functionRunnerClient{cc}
}

func (c *functionRunnerClient) Run(ctx context.Context, opts ...grpc1.CallOption) (FunctionRunner_RunClient, error) {
	stream, err := grpc1.NewClientStream(ctx, &_FunctionRunner_serviceDesc.Streams[0], c.cc, "/grpc.FunctionRunner/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &functionRunnerRunClient{stream}
	return x, nil
}

type FunctionRunner_RunClient interface {
	Send(*Data) error
	Recv() (*Data, error)
	grpc1.ClientStream
}

type functionRunnerRunClient struct {
	grpc1.ClientStream
}

func (x *functionRunnerRunClient) Send(m *Data) error {
	return x.ClientStream.SendMsg(m)
}

func (x *functionRunnerRunClient) Recv() (*Data, error) {
	m := new(Data)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for FunctionRunner service

type FunctionRunnerServer interface {
	Run(FunctionRunner_RunServer) error
}

func RegisterFunctionRunnerServer(s *grpc1.Server, srv FunctionRunnerServer) {
	s.RegisterService(&_FunctionRunner_serviceDesc, srv)
}

func _FunctionRunner_Run_Handler(srv interface{}, stream grpc1.ServerStream) error {
	return srv.(FunctionRunnerServer).Run(&functionRunnerRunServer{stream})
}

type FunctionRunner_RunServer interface {
	Send(*Data) error
	Recv() (*Data, error)
	grpc1.ServerStream
}

type functionRunnerRunServer struct {
	grpc1.ServerStream
}

func (x *functionRunnerRunServer) Send(m *Data) error {
	return x.ServerStream.SendMsg(m)
}

func (x *functionRunnerRunServer) Recv() (*Data, error) {
	m := new(Data)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FunctionRunner_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.FunctionRunner",
	HandlerType: (*FunctionRunnerServer)(nil),
	Methods:     []grpc1.MethodDesc{},
	Streams: []grpc1.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _FunctionRunner_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "frunner.proto",
}

func init() { proto.RegisterFile("frunner.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2b, 0x2a, 0xcd,
	0xcb, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56,
	0x92, 0xe2, 0x62, 0x71, 0x49, 0x2c, 0x49, 0x14, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x8d, 0x4c, 0xb9, 0xf8, 0xdc, 0x4a, 0xf3, 0x92,
	0x4b, 0x32, 0xf3, 0xf3, 0x82, 0xc0, 0x3a, 0x85, 0x94, 0xb9, 0x98, 0x83, 0x4a, 0xf3, 0x84, 0xb8,
	0xf4, 0x40, 0x7a, 0xf5, 0x40, 0x1a, 0xa5, 0x90, 0xd8, 0x4a, 0x0c, 0x1a, 0x8c, 0x06, 0x8c, 0x49,
	0x6c, 0x60, 0xf3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0x44, 0xae, 0xb9, 0x70, 0x00,
	0x00, 0x00,
}
